//! Self-reference suppression: detect and suppress findings that fire on
//! Camerata's own governance/corpus artifacts rather than application code.

use super::Finding;

/// True when a file is a governance or corpus artifact that Camerata itself emits or
/// ships. Self-referential suppression (Feature: scan-hygiene) applies ONLY to these
/// files — never to ordinary application code.
///
/// Conditions (any one is sufficient):
/// - `content` carries the `<!-- Generated by Camerata` header that Camerata writes into
///   every AGENTS.md and CONVENTIONS.md it emits.
/// - The path is under `.camerata/` (project-level governance config).
/// - The path contains a `principles/` segment AND ends with `.toml` (a rule corpus TOML).
///
/// `crates/gateway/src/lib.rs` (the detector source) is intentionally outside this
/// predicate — it is application source handled by repo-level scan exclusion or
/// `camerata:allow`, not by this mechanism.
pub fn is_governance_or_corpus_artifact(path: &str, content: &str) -> bool {
    if content.contains("<!-- Generated by Camerata") {
        return true;
    }
    // Path is under .camerata/ (project-level governance config).
    if path.starts_with(".camerata/") || path.contains("/.camerata/") {
        return true;
    }
    // Corpus TOML: a .toml file under a `principles/` path segment.
    if path.ends_with(".toml") && path.split('/').any(|s| s == "principles") {
        return true;
    }
    false
}

/// True when `snippet` is contained as a normalised substring of any corpus
/// descriptive text string. Normalisation: trim + lowercase on both sides.
///
/// An empty snippet never matches — zero-length substrings are vacuously contained
/// everywhere and would suppress every finding in a governance file.
pub fn is_self_referential_snippet(snippet: &str, corpus_texts: &[String]) -> bool {
    let needle = snippet.trim().to_lowercase();
    if needle.is_empty() {
        return false;
    }
    corpus_texts
        .iter()
        .any(|text| text.to_lowercase().contains(&needle))
}

/// Collect all descriptive text from a loaded rule set: title, summary, decision_why,
/// and each option's directive and why. Used to cross-reference scan snippets against
/// rule descriptions for self-referential suppression.
pub fn corpus_texts_from_ruleset(set: &camerata_rules::RuleSet) -> Vec<String> {
    let mut texts = Vec::new();
    for rule in set.iter() {
        texts.push(rule.title.clone());
        texts.push(rule.summary.clone());
        if let Some(why) = &rule.decision_why {
            texts.push(why.clone());
        }
        for opt in &rule.options {
            texts.push(opt.directive.clone());
            texts.push(opt.why.clone());
        }
    }
    texts
}

/// Mark findings in governance/corpus files as `suppressed-self-reference` when the
/// matched snippet is corpus description text rather than a real violation.
///
/// Both conditions must hold:
/// 1. The file is a governance/corpus artifact (`is_governance_or_corpus_artifact`).
/// 2. The matched snippet appears in the corpus descriptive text (`is_self_referential_snippet`).
///
/// Outside governance files, findings are NEVER touched — a real `verify=False` in
/// production code stays `active` even though some rule description contains that string.
///
/// A real secret pasted into CONVENTIONS.md that is NOT in any rule description also
/// stays `active` (condition 2 fails).
///
/// Only findings already marked `active` are touched; inline/baseline suppressions are
/// already classified and must not be downgraded.
pub fn suppress_self_referential(
    findings: &mut Vec<Finding>,
    files: &[(String, String)],
    corpus_texts: &[String],
) {
    // Build a quick path→content lookup to check the Generated-by marker per file.
    let content_map: std::collections::HashMap<&str, &str> = files
        .iter()
        .map(|(p, c)| (p.as_str(), c.as_str()))
        .collect();

    for f in findings.iter_mut() {
        // Only touch active findings — inline/baseline suppressions are already set.
        if f.status != "active" {
            continue;
        }
        let content = content_map.get(f.path.as_str()).copied().unwrap_or("");
        if is_governance_or_corpus_artifact(&f.path, content)
            && is_self_referential_snippet(&f.snippet, corpus_texts)
        {
            f.status = "suppressed-self-reference".to_string();
            f.detail.push_str(
                " (self-referential: matches a rule's own description; not a real finding)",
            );
        }
    }
}
