//! {{APP_NAME}} — {{APP_DESCRIPTION}}
//!
//! Generated by the Camerata Rust-fullstack PWA scaffolder. Dioxus fullstack
//! (server functions) + Axum; a responsive, installable PWA; no database, no
//! end-user auth by default (see `CONVENTIONS.md`).

mod app;
pub mod components;
pub mod pages;
pub mod routes;
pub mod server_fns;

pub use app::App;

#[cfg(target_arch = "wasm32")]
pub mod wasm_bridge;

#[cfg(not(target_arch = "wasm32"))]
pub mod server;
