//! Arm: install the approved rules into each repo via a governance PR.
//!
//! The EMITTED format is deliberately different from the user-facing rule TOML
//! (which carries `[[option]]` alternatives, `[decision]`, labels, `why`). Arm
//! emits only the project's ADOPTED position — one unambiguous directive per rule
//! — partitioned the way camerata-ai's `emit` does it:
//!
//! - **prose** rules -> `AGENTS.md` (behavioral, judged by the agent)
//! - **structured / mechanical** rules -> `CONVENTIONS.md` (citable by id; mechanical
//!   rules carry a `_Conformance:_` line)
//!
//! plus a `.camerata/rules.json` gate config listing the armed rule ids. This module
//! reproduces camerata-ai's `emit::render` block format faithfully (it is not on
//! crates.io to depend on). The architect-only fields are never emitted: the
//! consumer agent sees one instruction, not the curation surface.

use serde::{Deserialize, Serialize};

/// One rule to install, fully resolved by the UI: `directive` is the chosen
/// alternative's text (or the default's), already selected at curation time.
#[derive(Debug, Clone, Deserialize)]
pub struct ArmRule {
    /// Stable rule id.
    pub id: String,
    /// Human title.
    pub title: String,
    /// The adopted directive — the ONLY rule body emitted into the prose/conventions
    /// files.
    pub directive: String,
    /// The chosen alternative's option id, recorded in the gate config so the Rules
    /// screen can reconcile the repo back to the source rule's chosen alternative.
    #[serde(default)]
    pub option: Option<String>,
    /// `prose` | `structured` | `mechanical` (partitions AGENTS.md vs CONVENTIONS.md).
    pub enforcement: String,
    /// Optional conformance test (mechanical rules) -> the `_Conformance:_` line.
    #[serde(default)]
    pub conformance: Option<String>,
    /// The repos this rule is installed into (its placement).
    pub repos: Vec<String>,
}

/// One entry in a repo's `.camerata/rules.json` gate config: the applied rule id +
/// the chosen alternative. This is the LINK the Rules screen reconciles against the
/// corpus source rule (which holds the full alternatives + context).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GateRule {
    /// The rule id.
    pub id: String,
    /// The chosen alternative option id (None for single-variant rules).
    #[serde(default)]
    pub option: Option<String>,
}

const AGENTS_HEADER: &str = "<!-- Generated by Camerata. Edit the rule selection, not this file. -->\n\n\
# AGENTS.md\n\n\
This file is the authoritative source of architectural and behavioral commitments the AI agent applies when writing or modifying code in this project. Each block below states a single directive the agent follows at code-author time.\n\n\
These are prose-enforcement rules: the agent reads and respects them by judgment, not by lint or compiler check. They were adopted from the Camerata principle library by the project's architect, and represent committed choices, not suggestions.\n\n\
The companion file CONVENTIONS.md holds this project's structured and mechanical conventions, organized by citable rule ID.\n\n---\n\n";

const CONVENTIONS_HEADER: &str = "<!-- Generated by Camerata. Edit the rule selection, not this file. -->\n\n\
# CONVENTIONS.md\n\n\
This file is the authoritative source of structured and mechanical conventions this project follows. Each block states a rule with a stable citable ID that reviewers and the AI agent reference in commits, PR descriptions, and code reviews.\n\n\
These conventions were adopted from the Camerata principle library by the project's architect, and represent committed choices, not suggestions. Structured rules are verified by code review and citation; mechanical rules can be enforced by lint, type-system, or CI checks. Cite a rule's ID when applying it (for example, per RUST-DOMAIN-6).\n\n\
The companion file AGENTS.md holds this project's prose-enforcement directives.\n\n---\n\n";

/// Render one rule as a markdown block — faithful to camerata-ai `emit::render`:
/// `### {id} — {title}` then the directive, then (mechanical only) a conformance
/// line. Architect-only fields are not emitted.
pub fn render_rule(r: &ArmRule) -> String {
    let mut s = String::new();
    s.push_str(&format!("### {} — {}\n", r.id, r.title));
    s.push_str(&format!("{}\n", r.directive.trim()));
    if r.enforcement == "mechanical" {
        if let Some(c) = &r.conformance {
            if !c.trim().is_empty() {
                s.push_str(&format!("\n_Conformance:_ {}\n", c.trim()));
            }
        }
    }
    s.push('\n');
    s
}

fn render_file(header: &str, rules: &[&ArmRule]) -> String {
    let mut s = String::from(header);
    for r in rules {
        s.push_str(&render_rule(r));
    }
    s
}

/// Render one custom rule as a markdown block (camerata-ai's CUSTOM shape).
fn render_custom(c: &crate::project::CustomRule) -> String {
    let domain = if c.domain.trim().is_empty() {
        "*"
    } else {
        c.domain.trim()
    };
    format!(
        "### CUSTOM-{} _(custom · domain: {})_\n{}\n\n",
        c.name.trim(),
        domain,
        c.body.trim()
    )
}

/// The files to install into ONE repo: AGENTS.md (prose base rules + the project's
/// CUSTOM rules), CONVENTIONS.md (structured/mechanical base), and
/// `.camerata/rules.json` (the gate config: every applied rule id incl. custom).
///
/// CRITICAL INVARIANT: `custom` is the project's custom rules, ALWAYS carried into
/// the emit. A re-emit of base rules therefore never drops a custom rule — custom
/// rules disappear only when the user explicitly removes them from the project.
/// Pure.
pub fn arm_files_for_repo(
    rules: &[&ArmRule],
    custom: &[&crate::project::CustomRule],
) -> Vec<(String, String)> {
    let prose: Vec<&ArmRule> = rules
        .iter()
        .filter(|r| r.enforcement == "prose")
        .copied()
        .collect();
    let structured: Vec<&ArmRule> = rules
        .iter()
        .filter(|r| r.enforcement != "prose")
        .copied()
        .collect();

    let mut files = Vec::new();

    // AGENTS.md: prose base rules + custom rules (both are agent-judged prose).
    if !prose.is_empty() || !custom.is_empty() {
        let mut agents = render_file(AGENTS_HEADER, &prose);
        for c in custom {
            agents.push_str(&render_custom(c));
        }
        files.push(("AGENTS.md".to_string(), agents));
    }
    if !structured.is_empty() {
        files.push((
            "CONVENTIONS.md".to_string(),
            render_file(CONVENTIONS_HEADER, &structured),
        ));
    }

    // Gate config: base rules (id + chosen alternative) AND the custom rules (as
    // CUSTOM-<name>), so reconcile sees the custom rules already in the emit and
    // an upsert carries them forward rather than silently dropping them.
    let mut gate: Vec<GateRule> = rules
        .iter()
        .map(|r| GateRule {
            id: r.id.clone(),
            option: r.option.clone(),
        })
        .collect();
    for c in custom {
        gate.push(GateRule {
            id: format!("CUSTOM-{}", c.name.trim()),
            option: None,
        });
    }
    files.push((
        ".camerata/rules.json".to_string(),
        serde_json::to_string_pretty(&gate).unwrap_or_else(|_| "[]".to_string()),
    ));
    files
}

/// Group resolved rules by the repo they install into.
pub fn rules_by_repo(rules: &[ArmRule]) -> std::collections::BTreeMap<String, Vec<&ArmRule>> {
    let mut map: std::collections::BTreeMap<String, Vec<&ArmRule>> = std::collections::BTreeMap::new();
    for r in rules {
        for repo in &r.repos {
            map.entry(repo.clone()).or_default().push(r);
        }
    }
    map
}

/// The branch Camerata opens its governance PR from.
pub const ARM_BRANCH: &str = "camerata/onboard-governance";

/// Install `files` into `owner/repo` on a governance branch and open a PR. Returns
/// the PR URL. Needs Contents + PR write on the token. Tolerant of a pre-existing
/// branch (updates the files) and a pre-existing PR (returns it).
pub async fn arm_repo(
    owner: &str,
    repo: &str,
    token: &str,
    files: &[(String, String)],
) -> anyhow::Result<String> {
    use base64::Engine as _;
    use camerata_worktracker::{HttpTransport, ReqwestTransport};

    let transport = ReqwestTransport::new(format!("Bearer {token}"))?;
    let api = "https://api.github.com";

    // 1. Default branch + its head sha.
    let meta = transport.get(&format!("{api}/repos/{owner}/{repo}")).await?;
    if !(200..300).contains(&meta.status) {
        anyhow::bail!("GET repo {owner}/{repo}: HTTP {} {}", meta.status, meta.body);
    }
    let base = serde_json::from_str::<serde_json::Value>(&meta.body)?["default_branch"]
        .as_str()
        .unwrap_or("main")
        .to_string();
    let head = transport
        .get(&format!("{api}/repos/{owner}/{repo}/git/ref/heads/{base}"))
        .await?;
    if !(200..300).contains(&head.status) {
        anyhow::bail!("GET head ref: HTTP {} {}", head.status, head.body);
    }
    let head_sha = serde_json::from_str::<serde_json::Value>(&head.body)?["object"]["sha"]
        .as_str()
        .unwrap_or_default()
        .to_string();

    // 2. Create the branch (tolerate "already exists").
    let ref_body = serde_json::json!({
        "ref": format!("refs/heads/{ARM_BRANCH}"),
        "sha": head_sha,
    });
    let created = transport
        .post(&format!("{api}/repos/{owner}/{repo}/git/refs"), &ref_body.to_string())
        .await?;
    if !(200..300).contains(&created.status) && created.status != 422 {
        anyhow::bail!("create branch: HTTP {} {}", created.status, created.body);
    }

    // 3. PUT each file on the branch (include the current sha when it exists).
    for (path, content) in files {
        let existing = transport
            .get(&format!("{api}/repos/{owner}/{repo}/contents/{path}?ref={ARM_BRANCH}"))
            .await?;
        let sha = if (200..300).contains(&existing.status) {
            serde_json::from_str::<serde_json::Value>(&existing.body)
                .ok()
                .and_then(|v| v["sha"].as_str().map(String::from))
        } else {
            None
        };
        let encoded = base64::engine::general_purpose::STANDARD.encode(content.as_bytes());
        let mut put = serde_json::json!({
            "message": format!("chore(camerata): governance — {path}"),
            "content": encoded,
            "branch": ARM_BRANCH,
        });
        if let Some(sha) = sha {
            put["sha"] = serde_json::json!(sha);
        }
        let resp = transport
            .put(&format!("{api}/repos/{owner}/{repo}/contents/{path}"), &put.to_string())
            .await?;
        if !(200..300).contains(&resp.status) {
            anyhow::bail!("PUT {path}: HTTP {} {}", resp.status, resp.body);
        }
    }

    // 4. Open the PR (tolerate "already exists").
    let pr_body = serde_json::json!({
        "title": "Camerata: install governance",
        "head": ARM_BRANCH,
        "base": base,
        "body": "Installs the approved Camerata ruleset: AGENTS.md / CONVENTIONS.md \
                 (the adopted directives) and .camerata/rules.json (the gate config). \
                 Generated from the brownfield onboarding selection.",
    });
    let pr = transport
        .post(&format!("{api}/repos/{owner}/{repo}/pulls"), &pr_body.to_string())
        .await?;
    if (200..300).contains(&pr.status) {
        let v: serde_json::Value = serde_json::from_str(&pr.body)?;
        return Ok(v["html_url"].as_str().unwrap_or_default().to_string());
    }
    // A PR for this head may already exist — find and return it.
    if pr.status == 422 {
        let list = transport
            .get(&format!("{api}/repos/{owner}/{repo}/pulls?head={owner}:{ARM_BRANCH}&state=open"))
            .await?;
        if let Ok(serde_json::Value::Array(arr)) = serde_json::from_str(&list.body) {
            if let Some(first) = arr.first() {
                return Ok(first["html_url"].as_str().unwrap_or_default().to_string());
            }
        }
    }
    anyhow::bail!("open PR: HTTP {} {}", pr.status, pr.body)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rule(id: &str, enf: &str, repos: &[&str]) -> ArmRule {
        ArmRule {
            id: id.to_string(),
            title: format!("Title {id}"),
            directive: format!("Directive for {id}."),
            option: None,
            enforcement: enf.to_string(),
            conformance: if enf == "mechanical" {
                Some("a deterministic check".to_string())
            } else {
                None
            },
            repos: repos.iter().map(|s| s.to_string()).collect(),
        }
    }

    #[test]
    fn render_block_matches_emit_shape() {
        let r = rule("RUST-DOMAIN-6", "mechanical", &["me/api"]);
        let block = render_rule(&r);
        assert!(block.starts_with("### RUST-DOMAIN-6 — Title RUST-DOMAIN-6\n"));
        assert!(block.contains("Directive for RUST-DOMAIN-6."));
        assert!(block.contains("_Conformance:_ a deterministic check"));
    }

    #[test]
    fn prose_omits_conformance_line() {
        let r = rule("PROSE-1", "prose", &["me/api"]);
        assert!(!render_rule(&r).contains("_Conformance:_"));
    }

    #[test]
    fn files_partition_prose_and_structured_plus_gate_config() {
        let rules = [
            rule("P-1", "prose", &["me/api"]),
            rule("S-1", "structured", &["me/api"]),
            rule("M-1", "mechanical", &["me/api"]),
        ];
        let refs: Vec<&ArmRule> = rules.iter().collect();
        let files = arm_files_for_repo(&refs, &[]);
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"AGENTS.md"));
        assert!(names.contains(&"CONVENTIONS.md"));
        assert!(names.contains(&".camerata/rules.json"));

        let agents = &files.iter().find(|(n, _)| n == "AGENTS.md").unwrap().1;
        assert!(agents.contains("P-1") && !agents.contains("S-1"), "prose only in AGENTS.md");
        let conv = &files.iter().find(|(n, _)| n == "CONVENTIONS.md").unwrap().1;
        assert!(conv.contains("S-1") && conv.contains("M-1") && !conv.contains("P-1"));
        let gate = &files.iter().find(|(n, _)| n == ".camerata/rules.json").unwrap().1;
        assert!(gate.contains("P-1") && gate.contains("S-1") && gate.contains("M-1"));
    }

    #[test]
    fn custom_rules_are_carried_into_the_emit() {
        // A re-emit of only base rules must still include the project's custom rule.
        let base = [rule("S-1", "structured", &["me/api"])];
        let base_refs: Vec<&ArmRule> = base.iter().collect();
        let custom = crate::project::CustomRule {
            name: "house-style".into(),
            body: "Prefer X over Y.".into(),
            domain: "*".into(),
        };
        let files = arm_files_for_repo(&base_refs, &[&custom]);
        // The custom rule appears in AGENTS.md...
        let agents = &files.iter().find(|(n, _)| n == "AGENTS.md").unwrap().1;
        assert!(agents.contains("CUSTOM-house-style"));
        assert!(agents.contains("Prefer X over Y."));
        // ...and in the gate config, so reconcile sees it and an upsert keeps it.
        let gate = &files.iter().find(|(n, _)| n == ".camerata/rules.json").unwrap().1;
        assert!(gate.contains("CUSTOM-house-style"));
    }

    #[test]
    fn rules_group_by_repo() {
        let rules = vec![
            rule("A", "structured", &["me/api", "me/web"]),
            rule("B", "structured", &["me/web"]),
        ];
        let by = rules_by_repo(&rules);
        assert_eq!(by.get("me/api").unwrap().len(), 1);
        assert_eq!(by.get("me/web").unwrap().len(), 2);
    }
}
