//! Arm: install the approved rules into each repo via a governance PR.
//!
//! The EMITTED format is deliberately different from the user-facing rule TOML
//! (which carries `[[option]]` alternatives, `[decision]`, labels, `why`). Arm
//! emits only the project's ADOPTED position — one unambiguous directive per rule
//! — partitioned the way camerata-ai's `emit` does it:
//!
//! - **prose** rules -> `AGENTS.md` (behavioral, judged by the agent)
//! - **structured / mechanical / architectural** rules -> `CONVENTIONS.md` (citable by id;
//!   mechanical and architectural rules carry a `_Conformance:_` line and are wired into the
//!   CI-tier governance workflow rather than the write-time gate)
//!
//! plus a `.camerata/rules.json` gate config listing the armed rule ids. This module
//! reproduces camerata-ai's `emit::render` block format faithfully (it is not on
//! crates.io to depend on). The architect-only fields are never emitted: the
//! consumer agent sees one instruction, not the curation surface.

use serde::{Deserialize, Serialize};

/// One rule to install, fully resolved by the UI: `directive` is the chosen
/// alternative's text (or the default's), already selected at curation time.
#[derive(Debug, Clone, Deserialize)]
pub struct ArmRule {
    /// Stable rule id.
    pub id: String,
    /// Human title.
    pub title: String,
    /// The adopted directive — the ONLY rule body emitted into the prose/conventions
    /// files.
    pub directive: String,
    /// The chosen alternative's option id, recorded in the gate config so the Rules
    /// screen can reconcile the repo back to the source rule's chosen alternative.
    #[serde(default)]
    pub option: Option<String>,
    /// `prose` | `structured` | `mechanical` | `architectural` (partitions AGENTS.md vs
    /// CONVENTIONS.md, and which rules get a CI-tier check).
    pub enforcement: String,
    /// `repo-local` | `cross-repo` | `process`. Only repo-local rules are emitted
    /// into repo files; cross-repo + process rules are project-level (the gates read
    /// them from the project store), so they are saved to the project, not the repos.
    #[serde(default)]
    pub scope: String,
    /// Optional conformance test (mechanical rules) -> the `_Conformance:_` line.
    #[serde(default)]
    pub conformance: Option<String>,
    /// The repos this rule is installed into (its placement).
    pub repos: Vec<String>,
}

/// One entry in a repo's `.camerata/rules.json` gate config: the applied rule id +
/// the chosen alternative. This is the LINK the Rules screen reconciles against the
/// corpus source rule (which holds the full alternatives + context).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GateRule {
    /// The rule id.
    pub id: String,
    /// The chosen alternative option id (None for single-variant rules).
    #[serde(default)]
    pub option: Option<String>,
}

const AGENTS_HEADER: &str = "<!-- Generated by Camerata. Edit the rule selection, not this file. -->\n\n\
# AGENTS.md\n\n\
This file is the authoritative source of architectural and behavioral commitments the AI agent applies when writing or modifying code in this project. Each block below states a single directive the agent follows at code-author time.\n\n\
These are prose-enforcement rules: the agent reads and respects them by judgment, not by lint or compiler check. They were adopted from the Camerata principle library by the project's architect, and represent committed choices, not suggestions.\n\n\
The companion file CONVENTIONS.md holds this project's structured and mechanical conventions, organized by citable rule ID.\n\n---\n\n";

const CONVENTIONS_HEADER: &str = "<!-- Generated by Camerata. Edit the rule selection, not this file. -->\n\n\
# CONVENTIONS.md\n\n\
This file is the authoritative source of structured and mechanical conventions this project follows. Each block states a rule with a stable citable ID that reviewers and the AI agent reference in commits, PR descriptions, and code reviews.\n\n\
These conventions were adopted from the Camerata principle library by the project's architect, and represent committed choices, not suggestions. Structured rules are verified by code review and citation; mechanical rules can be enforced by lint, type-system, or CI checks. Cite a rule's ID when applying it (for example, per RUST-DOMAIN-6).\n\n\
The companion file AGENTS.md holds this project's prose-enforcement directives.\n\n---\n\n";

/// Whether an `ArmRule.enforcement` string names a CI-tier (deterministic, integration-stage)
/// check rather than the write-time gate or human review. Both `mechanical` (lint / query-plan
/// / migration audit) and `architectural` (AST static analysis) are CI-tier; they carry a
/// `_Conformance:_` line and are wired into the governance workflow. Mirrors
/// [`camerata_rules::EnforcementKind::is_ci_enforced`].
fn is_ci_tier(enforcement: &str) -> bool {
    matches!(enforcement, "mechanical" | "architectural")
}

/// Render one rule as a markdown block — faithful to camerata-ai `emit::render`:
/// `### {id} — {title}` then the directive, then (CI-tier rules only) a conformance
/// line. Architect-only fields are not emitted.
pub fn render_rule(r: &ArmRule) -> String {
    let mut s = String::new();
    s.push_str(&format!("### {} — {}\n", r.id, r.title));
    s.push_str(&format!("{}\n", r.directive.trim()));
    if is_ci_tier(&r.enforcement) {
        if let Some(c) = &r.conformance {
            if !c.trim().is_empty() {
                s.push_str(&format!("\n_Conformance:_ {}\n", c.trim()));
            }
        }
    }
    s.push('\n');
    s
}

fn render_file(header: &str, rules: &[&ArmRule]) -> String {
    let mut s = String::from(header);
    for r in rules {
        s.push_str(&render_rule(r));
    }
    s
}

/// Render one custom rule as a markdown block (camerata-ai's CUSTOM shape).
fn render_custom(c: &crate::project::CustomRule) -> String {
    let domain = if c.domain.trim().is_empty() {
        "*"
    } else {
        c.domain.trim()
    };
    format!(
        "### CUSTOM-{} _(custom · domain: {})_\n{}\n\n",
        c.name.trim(),
        domain,
        c.body.trim()
    )
}

/// The files to install into ONE repo: AGENTS.md (prose base rules + the project's
/// CUSTOM rules), CONVENTIONS.md (structured/mechanical base), and
/// `.camerata/rules.json` (the gate config: every applied rule id incl. custom).
///
/// CRITICAL INVARIANT: `custom` is the project's custom rules, ALWAYS carried into
/// the emit. A re-emit of base rules therefore never drops a custom rule — custom
/// rules disappear only when the user explicitly removes them from the project.
/// Pure.
pub fn arm_files_for_repo(
    rules: &[&ArmRule],
    custom: &[&crate::project::CustomRule],
) -> Vec<(String, String)> {
    let prose: Vec<&ArmRule> = rules
        .iter()
        .filter(|r| r.enforcement == "prose")
        .copied()
        .collect();
    let structured: Vec<&ArmRule> = rules
        .iter()
        .filter(|r| r.enforcement != "prose")
        .copied()
        .collect();

    let mut files = Vec::new();

    // AGENTS.md: prose base rules + custom rules (both are agent-judged prose).
    if !prose.is_empty() || !custom.is_empty() {
        let mut agents = render_file(AGENTS_HEADER, &prose);
        for c in custom {
            agents.push_str(&render_custom(c));
        }
        files.push(("AGENTS.md".to_string(), agents));
    }
    if !structured.is_empty() {
        files.push((
            "CONVENTIONS.md".to_string(),
            render_file(CONVENTIONS_HEADER, &structured),
        ));
    }

    // Gate config: base rules (id + chosen alternative) AND the custom rules (as
    // CUSTOM-<name>), so reconcile sees the custom rules already in the emit and
    // an upsert carries them forward rather than silently dropping them.
    let mut gate: Vec<GateRule> = rules
        .iter()
        .map(|r| GateRule {
            id: r.id.clone(),
            option: r.option.clone(),
        })
        .collect();
    for c in custom {
        gate.push(GateRule {
            id: format!("CUSTOM-{}", c.name.trim()),
            option: None,
        });
    }
    files.push((
        ".camerata/rules.json".to_string(),
        serde_json::to_string_pretty(&gate).unwrap_or_else(|_| "[]".to_string()),
    ));

    // CI-tier (integration-stage) enforcement: mechanical rules are NOT write-time
    // gate checks — their conformance is a CI mechanism (lint, query-plan, migration
    // audit, AST). Emit them into `.camerata/ci-checks.json` as the declarative
    // integration config (the parallel to the gate's rules.json) + a workflow scaffold
    // that surfaces them, so the strict mechanical rules are enforced where they belong.
    let mechanical: Vec<&ArmRule> = rules
        .iter()
        .filter(|r| is_ci_tier(&r.enforcement))
        .copied()
        .collect();
    if !mechanical.is_empty() {
        let checks: Vec<serde_json::Value> = mechanical
            .iter()
            .map(|r| {
                serde_json::json!({
                    "id": r.id,
                    "title": r.title,
                    "directive": r.directive,
                    "conformance": r.conformance,
                })
            })
            .collect();
        files.push((
            ".camerata/ci-checks.json".to_string(),
            serde_json::to_string_pretty(&checks).unwrap_or_else(|_| "[]".to_string()),
        ));
        files.push((
            ".github/workflows/camerata-governance.yml".to_string(),
            ci_workflow(&mechanical),
        ));
    }
    files
}

/// The GitHub Actions workflow scaffold that runs the integration-tier (mechanical)
/// governance checks. It surfaces each declared check from `.camerata/ci-checks.json`
/// and is the hook where the team wires its stack's enforcement (ESLint
/// no-restricted-syntax, a migration/index audit, an AST lint), so a PR that violates a
/// mechanical rule fails CI — the same strictness as the gate, at the right stage.
fn ci_workflow(mechanical: &[&ArmRule]) -> String {
    let mut checks = String::new();
    for r in mechanical {
        checks.push_str(&format!("          echo '  - {} — {}'\n", r.id, r.title));
    }
    format!(
        "# Generated by Camerata. Mechanical (CI-tier) governance checks; declared in\n\
         # .camerata/ci-checks.json. Wire each rule's enforcement into the step below.\n\
         name: Camerata governance\n\
         on: [pull_request]\n\
         jobs:\n\
         \x20 governance:\n\
         \x20   runs-on: ubuntu-latest\n\
         \x20   steps:\n\
         \x20     - uses: actions/checkout@v4\n\
         \x20     - name: Declared mechanical governance checks\n\
         \x20       run: |\n\
         \x20         echo 'Camerata mechanical rules to enforce (see .camerata/ci-checks.json):'\n\
         {checks}\
         \x20         echo 'Wire each rule into its stack mechanism (lint / query-plan / AST) here.'\n"
    )
}

/// Given a repo's resolved local directory and the list of file paths Camerata is
/// ABOUT TO WRITE for that repo (the `path` of each `(path, content)` pair the apply
/// flow produces), return the subset of those paths that ALREADY EXIST on disk and
/// would therefore be OVERWRITTEN by Apply.
///
/// This is intentionally driven by the exact paths the apply flow computed (rather than
/// a hardcoded list), so it can never warn about a file Camerata is not going to write,
/// and never miss one it is. Paths are joined onto `dir` and checked against the working
/// tree (the architect's checked-out clone, which is what Apply mutates).
///
/// Returned paths are the repo-relative paths (same strings that were passed in), sorted
/// and de-duplicated, so the UI can list exactly which files in which repo will be
/// clobbered. Pure of side effects (only stats the filesystem).
pub fn existing_governance_files(dir: &std::path::Path, will_write: &[String]) -> Vec<String> {
    let mut existing: Vec<String> = will_write
        .iter()
        .filter(|rel| {
            let candidate = dir.join(rel.as_str());
            candidate.exists()
        })
        .cloned()
        .collect();
    existing.sort();
    existing.dedup();
    existing
}

/// Group resolved rules by the repo they install into.
pub fn rules_by_repo(rules: &[ArmRule]) -> std::collections::BTreeMap<String, Vec<&ArmRule>> {
    let mut map: std::collections::BTreeMap<String, Vec<&ArmRule>> =
        std::collections::BTreeMap::new();
    for r in rules {
        for repo in &r.repos {
            map.entry(repo.clone()).or_default().push(r);
        }
    }
    map
}

/// The branch Camerata opens its governance PR from.
pub const ARM_BRANCH: &str = "camerata/onboard-governance";

/// Install `files` into `owner/repo` on the governance branch (creating it from the default
/// branch if needed) via the GitHub Contents API, and return the BRANCH's web URL. Does NOT
/// open a PR — Camerata never opens a PR automatically; the architect opens it explicitly with
/// the "Open governance PR" button. Needs Contents write on the token. Tolerant of a
/// pre-existing branch (updates the files in place).
pub async fn arm_repo(
    owner: &str,
    repo: &str,
    token: &str,
    files: &[(String, String)],
) -> anyhow::Result<String> {
    use base64::Engine as _;
    use camerata_worktracker::{HttpTransport, ReqwestTransport};

    let transport = ReqwestTransport::new(format!("Bearer {token}"))?;
    let api = "https://api.github.com";

    // 1. Default branch + its head sha.
    let meta = transport
        .get(&format!("{api}/repos/{owner}/{repo}"))
        .await?;
    if !(200..300).contains(&meta.status) {
        anyhow::bail!(
            "GET repo {owner}/{repo}: HTTP {} {}",
            meta.status,
            meta.body
        );
    }
    let base = serde_json::from_str::<serde_json::Value>(&meta.body)?["default_branch"]
        .as_str()
        .unwrap_or("main")
        .to_string();
    let head = transport
        .get(&format!("{api}/repos/{owner}/{repo}/git/ref/heads/{base}"))
        .await?;
    if !(200..300).contains(&head.status) {
        anyhow::bail!("GET head ref: HTTP {} {}", head.status, head.body);
    }
    let head_sha = serde_json::from_str::<serde_json::Value>(&head.body)?["object"]["sha"]
        .as_str()
        .unwrap_or_default()
        .to_string();

    // 2. Create the branch (tolerate "already exists").
    let ref_body = serde_json::json!({
        "ref": format!("refs/heads/{ARM_BRANCH}"),
        "sha": head_sha,
    });
    let created = transport
        .post(
            &format!("{api}/repos/{owner}/{repo}/git/refs"),
            &ref_body.to_string(),
        )
        .await?;
    if !(200..300).contains(&created.status) && created.status != 422 {
        anyhow::bail!("create branch: HTTP {} {}", created.status, created.body);
    }

    // 3. PUT each file on the branch (include the current sha when it exists).
    for (path, content) in files {
        let existing = transport
            .get(&format!(
                "{api}/repos/{owner}/{repo}/contents/{path}?ref={ARM_BRANCH}"
            ))
            .await?;
        let sha = if (200..300).contains(&existing.status) {
            serde_json::from_str::<serde_json::Value>(&existing.body)
                .ok()
                .and_then(|v| v["sha"].as_str().map(String::from))
        } else {
            None
        };
        let encoded = base64::engine::general_purpose::STANDARD.encode(content.as_bytes());
        let mut put = serde_json::json!({
            "message": format!("chore(camerata): governance — {path}"),
            "content": encoded,
            "branch": ARM_BRANCH,
        });
        if let Some(sha) = sha {
            put["sha"] = serde_json::json!(sha);
        }
        let resp = transport
            .put(
                &format!("{api}/repos/{owner}/{repo}/contents/{path}"),
                &put.to_string(),
            )
            .await?;
        if !(200..300).contains(&resp.status) {
            anyhow::bail!("PUT {path}: HTTP {} {}", resp.status, resp.body);
        }
    }

    // Camerata NEVER opens a PR automatically (only the explicit "Open governance PR" button
    // does, via `open_branch_pr`). This path stops at the pushed branch and returns its web URL
    // so the UI can link to it; the architect decides whether/when to open the PR.
    Ok(format!(
        "https://github.com/{owner}/{repo}/tree/{ARM_BRANCH}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rule(id: &str, enf: &str, repos: &[&str]) -> ArmRule {
        ArmRule {
            id: id.to_string(),
            title: format!("Title {id}"),
            directive: format!("Directive for {id}."),
            option: None,
            enforcement: enf.to_string(),
            scope: "repo-local".to_string(),
            conformance: if is_ci_tier(enf) {
                Some("a deterministic check".to_string())
            } else {
                None
            },
            repos: repos.iter().map(|s| s.to_string()).collect(),
        }
    }

    #[test]
    fn render_block_matches_emit_shape() {
        let r = rule("RUST-DOMAIN-6", "mechanical", &["me/api"]);
        let block = render_rule(&r);
        assert!(block.starts_with("### RUST-DOMAIN-6 — Title RUST-DOMAIN-6\n"));
        assert!(block.contains("Directive for RUST-DOMAIN-6."));
        assert!(block.contains("_Conformance:_ a deterministic check"));
    }

    #[test]
    fn prose_omits_conformance_line() {
        let r = rule("PROSE-1", "prose", &["me/api"]);
        assert!(!render_rule(&r).contains("_Conformance:_"));
    }

    #[test]
    fn files_partition_prose_and_structured_plus_gate_config() {
        let rules = [
            rule("P-1", "prose", &["me/api"]),
            rule("S-1", "structured", &["me/api"]),
            rule("M-1", "mechanical", &["me/api"]),
        ];
        let refs: Vec<&ArmRule> = rules.iter().collect();
        let files = arm_files_for_repo(&refs, &[]);
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"AGENTS.md"));
        assert!(names.contains(&"CONVENTIONS.md"));
        assert!(names.contains(&".camerata/rules.json"));

        let agents = &files.iter().find(|(n, _)| n == "AGENTS.md").unwrap().1;
        assert!(
            agents.contains("P-1") && !agents.contains("S-1"),
            "prose only in AGENTS.md"
        );
        let conv = &files.iter().find(|(n, _)| n == "CONVENTIONS.md").unwrap().1;
        assert!(conv.contains("S-1") && conv.contains("M-1") && !conv.contains("P-1"));
        let gate = &files
            .iter()
            .find(|(n, _)| n == ".camerata/rules.json")
            .unwrap()
            .1;
        assert!(gate.contains("P-1") && gate.contains("S-1") && gate.contains("M-1"));
    }

    #[test]
    fn mechanical_rules_emit_ci_checks_and_workflow() {
        let rules = [
            rule("S-1", "structured", &["me/api"]),
            rule("M-1", "mechanical", &["me/api"]),
        ];
        let refs: Vec<&ArmRule> = rules.iter().collect();
        let files = arm_files_for_repo(&refs, &[]);
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&".camerata/ci-checks.json"));
        assert!(names.contains(&".github/workflows/camerata-governance.yml"));

        // The CI checks list ONLY mechanical rules (S-1 is a doc convention, not CI).
        let ci = &files
            .iter()
            .find(|(n, _)| n == ".camerata/ci-checks.json")
            .unwrap()
            .1;
        assert!(ci.contains("M-1") && ci.contains("a deterministic check"));
        assert!(!ci.contains("S-1"));
        let wf = &files
            .iter()
            .find(|(n, _)| n.ends_with("camerata-governance.yml"))
            .unwrap()
            .1;
        assert!(wf.contains("M-1") && wf.contains("pull_request"));
    }

    #[test]
    fn architectural_rules_partition_to_conventions_and_ci() {
        // An architectural rule is citable (CONVENTIONS.md, not AGENTS.md), carries a
        // conformance line, and is wired into the CI governance workflow — exactly like
        // a mechanical rule, since both are CI-tier deterministic checks.
        let rules = [
            rule("P-1", "prose", &["me/api"]),
            rule("A-1", "architectural", &["me/api"]),
        ];
        let refs: Vec<&ArmRule> = rules.iter().collect();
        let files = arm_files_for_repo(&refs, &[]);

        let conv = &files.iter().find(|(n, _)| n == "CONVENTIONS.md").unwrap().1;
        assert!(
            conv.contains("A-1"),
            "architectural rule lands in CONVENTIONS.md"
        );
        assert!(
            conv.contains("_Conformance:_ a deterministic check"),
            "architectural rule carries a conformance line"
        );
        let agents = &files.iter().find(|(n, _)| n == "AGENTS.md").unwrap().1;
        assert!(
            !agents.contains("A-1"),
            "architectural rule is NOT in AGENTS.md"
        );

        let ci = &files
            .iter()
            .find(|(n, _)| n == ".camerata/ci-checks.json")
            .unwrap()
            .1;
        assert!(ci.contains("A-1"), "architectural rule is a CI-tier check");
        let wf = &files
            .iter()
            .find(|(n, _)| n.ends_with("camerata-governance.yml"))
            .unwrap()
            .1;
        assert!(
            wf.contains("A-1"),
            "architectural rule surfaces in the workflow"
        );
    }

    #[test]
    fn no_mechanical_rules_emits_no_ci_files() {
        let rules = [rule("S-1", "structured", &["me/api"])];
        let refs: Vec<&ArmRule> = rules.iter().collect();
        let files = arm_files_for_repo(&refs, &[]);
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(!names.contains(&".camerata/ci-checks.json"));
        assert!(!names.iter().any(|n| n.ends_with("camerata-governance.yml")));
    }

    #[test]
    fn custom_rules_are_carried_into_the_emit() {
        // A re-emit of only base rules must still include the project's custom rule.
        let base = [rule("S-1", "structured", &["me/api"])];
        let base_refs: Vec<&ArmRule> = base.iter().collect();
        let custom = crate::project::CustomRule {
            name: "house-style".into(),
            body: "Prefer X over Y.".into(),
            domain: "*".into(),
        };
        let files = arm_files_for_repo(&base_refs, &[&custom]);
        // The custom rule appears in AGENTS.md...
        let agents = &files.iter().find(|(n, _)| n == "AGENTS.md").unwrap().1;
        assert!(agents.contains("CUSTOM-house-style"));
        assert!(agents.contains("Prefer X over Y."));
        // ...and in the gate config, so reconcile sees it and an upsert keeps it.
        let gate = &files
            .iter()
            .find(|(n, _)| n == ".camerata/rules.json")
            .unwrap()
            .1;
        assert!(gate.contains("CUSTOM-house-style"));
    }

    #[test]
    fn existing_governance_files_reports_only_present_paths() {
        let dir = std::env::temp_dir().join(format!(
            "camerata-existing-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(dir.join(".camerata")).unwrap();
        std::fs::create_dir_all(dir.join(".github/workflows")).unwrap();

        // Create SOME of the files Camerata would write, not all.
        std::fs::write(dir.join("AGENTS.md"), "hand-written agents").unwrap();
        std::fs::write(dir.join(".camerata/baseline.json"), "{}").unwrap();
        std::fs::write(
            dir.join(".github/workflows/camerata-governance.yml"),
            "name: x",
        )
        .unwrap();

        let will_write = vec![
            "AGENTS.md".to_string(),
            "CONVENTIONS.md".to_string(),
            ".camerata/rules.json".to_string(),
            ".camerata/baseline.json".to_string(),
            ".github/workflows/camerata-governance.yml".to_string(),
        ];

        let existing = existing_governance_files(&dir, &will_write);

        // Exactly the three created files, sorted; not CONVENTIONS.md or rules.json.
        assert_eq!(
            existing,
            vec![
                ".camerata/baseline.json".to_string(),
                ".github/workflows/camerata-governance.yml".to_string(),
                "AGENTS.md".to_string(),
            ]
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn existing_governance_files_empty_when_nothing_present() {
        let dir = std::env::temp_dir().join(format!(
            "camerata-existing-empty-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let will_write = vec!["AGENTS.md".to_string(), ".camerata/rules.json".to_string()];
        assert!(existing_governance_files(&dir, &will_write).is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn existing_governance_files_ignores_unwritten_paths() {
        // A repo may have a CONVENTIONS.md that Camerata is NOT going to write this run
        // (no structured rules selected); it must not be reported.
        let dir = std::env::temp_dir().join(format!(
            "camerata-existing-unwritten-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("CONVENTIONS.md"), "hand-written").unwrap();
        std::fs::write(dir.join("AGENTS.md"), "hand-written").unwrap();
        // Only AGENTS.md is in this run's write set.
        let will_write = vec!["AGENTS.md".to_string()];
        let existing = existing_governance_files(&dir, &will_write);
        assert_eq!(existing, vec!["AGENTS.md".to_string()]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn rules_group_by_repo() {
        let rules = vec![
            rule("A", "structured", &["me/api", "me/web"]),
            rule("B", "structured", &["me/web"]),
        ];
        let by = rules_by_repo(&rules);
        assert_eq!(by.get("me/api").unwrap().len(), 1);
        assert_eq!(by.get("me/web").unwrap().len(), 2);
    }
}
